CREATE EXTENSION vector;

/*image_size enum 추가*/
CREATE TYPE image_size_enum AS ENUM (
  'SMALL', 'MEDIUM', 'LARGE'
);

CREATE TYPE "activity_enum" AS ENUM (
  'OFFLINE',
  'ONLINE',
  'HYBRID'
);

CREATE TYPE "purpose_enum" AS ENUM (
  'PROFILE',
  'POST',
  'PORTFOLIO'
);

CREATE TYPE "status_enum" AS ENUM (
  'ENROLLED',
  'LEAVE',
  'DEFERRED',
  'GRADUATED',
  'TRANSFER',
  'EXCHANGE',
  'OTHER'
);

CREATE TYPE "gender_enum" AS ENUM (
  'FEMALE',
  'MALE',
  'NONBINARY'
);

CREATE TYPE "recruit_status" AS ENUM (
  'OPEN',
  'CLOSED'
);

CREATE TABLE "field" (
  "field_id" int PRIMARY KEY NOT NULL,
  "field_name" varchar(50) NOT NULL
);

CREATE TABLE "role" (
  "role_id" int PRIMARY KEY NOT NULL,
  "field_id" int NOT NULL,
  "role_name" varchar(100) NOT NULL
);

CREATE TABLE "skill" (
  "field_id" int,
  "skill_id" int PRIMARY KEY NOT NULL,
  "skill_name" varchar(50) NOT NULL
);

CREATE TABLE "domain" (
  "domain_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "domain_name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "university" (
  "univ_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "univ_name" varchar(255)
);

/* file_size: 실제 사이즈, size_type: enum */
CREATE TABLE "image" (
  "image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image_url" varchar(512),
  "purpose" purpose_enum,
  "file_size" bigint,
  "size_type" image_size_enum
);

/*user는 postgresql에서 쓰는 시스템 키워드라서 오류 발생 --> users로 변경*/
/*user의 personality를 json이 아니라 jsonb로 하면 좋을 것 같엉! 이게 검색, 조회하기게 좋대!!*/
CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login_id" varchar(50) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "username" varchar(50) NOT NULL,
  "image_id" bigint,
  "main_role_id" int,
  "personality" jsonb,
  "jwt_role" varchar(20) NOT NULL DEFAULT 'USER',
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

/*refresh token table 추가*/
CREATE TABLE refresh_token (
  "refresh_token_id" BIGSERIAL PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "token" VARCHAR(512) NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "revoked" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  
  CONSTRAINT fk_refresh_token_user
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE "user_profile" (
  "user_id" bigint PRIMARY KEY,
  "email" varchar(100) NOT NULL,
  "university_id" bigint,
  "major" varchar(50),
  "status" status_enum,
  "gender" gender_enum,
  "entrance_year" int,
  "birth_year" int
);

CREATE TABLE "user_skill" (
  "user_skill_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "skill_id" int NOT NULL
);

CREATE TABLE "post" (
  "post_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "leader_id" bigint,
  "title" varchar(200),
  "prime_domain_id" int,
  "second_domain_id" int,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "post_info" (
  "pinfo_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint,
  "status" recruit_status DEFAULT 'OPEN',
  "recruit_sdate" TIMESTAMPTZ,
  "recruit_edate" TIMESTAMPTZ,

  "contact" varchar(255),
  "about_us" text,
  "team_culture" json,
  "seeking" text,
  "homepage_url" text,
  "image_id" bigint
);

CREATE TABLE "post_current_role" (
  "pcurrent_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint NOT NULL,
  "role_id" int NOT NULL,
  "count" int DEFAULT 1
);

CREATE TABLE "post_recruit_role" (
  "precruit_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint NOT NULL,
  "role_id" int NOT NULL,
  "count" int DEFAULT 1
);

/*pst_domain_exp 추가*/
CREATE TABLE "post_vector" (
  "post_id" bigint PRIMARY KEY,
  "pst_task_vector" vector(3072),
  "pst_trouble_vector" vector(3072),
  "pst_domain_exp" boolean,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "post_apply" (
  "apply_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "apply_date" TIMESTAMPTZ
);

/*postgresql이 대소문자 구분하는게 어려워서 STAR_text --> star_text로 바꿈*/
CREATE TABLE "portfolio" (
  "portfolio_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  "user_id" bigint NOT NULL,
  "title" varchar(200),
  "field_id" int,
  "role_id" int,
  "domain_id" int,

  "headcount" int,
  "image_id" bigint,
  "extern_url" text,

  "summary" varchar(200),
  "s_text" text,
  "t_text" text,
  "a_text" text,
  "r_text" text,
  
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "portfolio_vector" (
  "portfolio_id" bigint PRIMARY KEY,
  "ptf_task_vector" vector(3072),
  "ptf_trouble_vector" vector(3072),
  "updated_at" TIMESTAMPTZ
);

-- ==========================================
-- 1. Dimension Tables (기준 정보)
-- 전략: RESTRICT (기본값) - 삭제 금지
-- ==========================================
-- (옵션을 안 적으면 자동으로 RESTRICT가 됩니다!)

ALTER TABLE "role" ADD FOREIGN KEY ("field_id") REFERENCES "field" ("field_id");
ALTER TABLE "skill" ADD FOREIGN KEY ("field_id") REFERENCES "field" ("field_id");

-- Users의 role 참조는 삭제 금지 (직무가 사라지면 유저 정보가 꼬임)
ALTER TABLE "users" ADD FOREIGN KEY ("main_role_id") REFERENCES "role" ("role_id"); 
ALTER TABLE "user_profile" ADD FOREIGN KEY ("university_id") REFERENCES "university" ("univ_id");
ALTER TABLE "user_skill" ADD FOREIGN KEY ("skill_id") REFERENCES "skill" ("skill_id");

-- Post, Portfolio의 차원 정보 참조도 삭제 금지
ALTER TABLE "post" ADD FOREIGN KEY ("prime_domain_id") REFERENCES "domain" ("domain_id");
ALTER TABLE "post" ADD FOREIGN KEY ("second_domain_id") REFERENCES "domain" ("domain_id");
ALTER TABLE "post_current_role" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");
ALTER TABLE "post_recruit_role" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");
ALTER TABLE "portfolio" ADD FOREIGN KEY ("field_id") REFERENCES "field" ("field_id");
ALTER TABLE "portfolio" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");
ALTER TABLE "portfolio" ADD FOREIGN KEY ("domain_id") REFERENCES "domain" ("domain_id");


-- ==========================================
-- 2. User Relation (회원 관련)
-- 전략: CASCADE - 개발자가 회원 삭제시 싹 정리
-- ==========================================

-- 프로필, 스킬, 지원내역, 포폴은 회원의 소유물이므로 같이 삭제
ALTER TABLE "user_profile" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;
ALTER TABLE "user_skill" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;
ALTER TABLE "post_apply" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;
ALTER TABLE "portfolio" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;
ALTER TABLE "post" ADD FOREIGN KEY ("leader_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;

-- ==========================================
-- 3. Post Relation (공고 관련)
-- 전략: CASCADE - 공고 삭제시 부속 데이터 정리
-- ==========================================

ALTER TABLE "post_info" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_id") ON DELETE CASCADE;
ALTER TABLE "post_current_role" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_id") ON DELETE CASCADE;
ALTER TABLE "post_recruit_role" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_id") ON DELETE CASCADE;
ALTER TABLE "post_vector" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_id") ON DELETE CASCADE;
ALTER TABLE "post_apply" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_id") ON DELETE CASCADE;


-- ==========================================
-- 4. Portfolio Relation (포폴 관련)
-- 전략: CASCADE - 포폴 삭제시 벡터 정리
-- ==========================================

ALTER TABLE "portfolio_vector" ADD FOREIGN KEY ("portfolio_id") REFERENCES "portfolio" ("portfolio_id") ON DELETE CASCADE;


-- ==========================================
-- 5. Image Relation (이미지 관련)
-- 전략: SET DEFAULT - 이미지가 깨져도 본문은 살린다
-- ==========================================


ALTER TABLE "post_info" ADD FOREIGN KEY ("image_id") REFERENCES "image" ("image_id") ON DELETE SET NULL; -- post의 경우, NULL처리함 
ALTER TABLE "portfolio" ADD FOREIGN KEY ("image_id") REFERENCES "image" ("image_id") ON DELETE SET DEFAULT;
ALTER TABLE "users" ADD FOREIGN KEY ("image_id") REFERENCES "image" ("image_id") ON DELETE SET DEFAULT;



/*refresh token: 같은 토큰이 중복 저장되는걸 막기*/
CREATE UNIQUE INDEX ux_refresh_token_token ON refresh_token(token);

/*유저별 조회/정리 성능*/
CREATE INDEX ix_refresh_token_user_id ON refresh_token(user_id);

/*만료/정리 작업 성능*/
CREATE INDEX ix_refresh_token_expires_at ON refresh_token(expires_at);